### ISSUE TITLE
GET /human/search?q=前田こずえ

### ISSUE THREAD

**Issue by mksimpler** [mksimpler/leech-server#1]
Log
> 2017-09-20T11:46:53.378169+00:00 app[web.1]: TypeError: Cannot read property '0' of undefined
> 2017-09-20T11:46:53.378180+00:00 app[web.1]:     at leech.get.then.$ (/app/libs/crawlers/minnano-av.js:308:59)
> 2017-09-20T11:46:53.378182+00:00 app[web.1]:     at <anonymous>
> 2017-09-20T11:46:53.378183+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by mksimpler** [comment]
Fixed.
