### ISSUE TITLE
GET /movie/search?q=VENU-376 (choice first)

### ISSUE THREAD

**Issue by mksimpler** [mksimpler/leech-server#2]
Log

> 2017-09-21T05:12:54.548771+00:00 app[web.1]: TypeError: Cannot read property 'childNodes' of undefined
> 2017-09-21T05:12:54.548782+00:00 app[web.1]:     at leech.get.then.$ (/app/libs/crawlers/dmm.js:161:74)
> 2017-09-21T05:12:54.548784+00:00 app[web.1]:     at <anonymous>
> 2017-09-21T05:12:54.548785+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by mksimpler** [comment]
Fixed.
